# Everything you need to know about configuring the CMS can be found here:-
# https://www.netlifycms.org/docs/configuration-options/

backend:
  name: git-gateway # Netlify’s Git Gateway connects to Git provider’s API
  branch: master # Branch to update (master by default)

media_folder: "assets/img/uploads" # Folder where user uploaded files should go

publish_mode: editorial_workflow # Enable drafts

collections: # A list of collections the CMS should be able to edit
  # # POSTS
  # - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
  #   label: "Post" # Used in the UI, ie.: "New Post"
  #   folder: "_posts" # The path to the folder where the documents are stored
  #   sort: "date:desc" # Default is title:asc
  #   create: true # Allow users to create new documents in this collection
  #   slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  #   fields: # The fields each document in this collection have
  #     - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
  #     - {label: "Title", name: "title", widget: "string", tagname: "h1"}
  #     - label: "Author"
  #       name: "author"
  #       widget: "select"
  #       options:
  #         - { label: "Dan Urbanowicz", value: "dan_urbanowicz" }
  #         - { label: "John Doe", value: "john_doe" }
  #     - {label: "Publish Date", name: "date", widget: "datetime", format: "YYYY-MM-DD HH:MM:SS"}
  #     - {label: "Intro Paragraph", name: "intro_paragraph", widget: "markdown", required: false}
  #     - {label: "Body", name: "body", widget: "markdown", required: false}
  #     - {label: "Categories", name: "categories", widget: "string", required: false}
    # PAGES
  - name: "home" # used in routes, e.g. /admin/collections/home
    label: "Home Page" # Used in the UI
    delete: false
    editor:
      preview: false
    folder: "mainpage" # The path to the folder where the documents are stored
    sort: "title:asc"
    create: false # Don't allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template i.e. YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Permalink", name: "permalink", widget: "hidden"}
      - {label: "Section", name: "section", widget: "hidden", default: "{{name}}"}      
      # - {label: "Body", name: "body", widget: "markdown",}
      - {label: "Image 1", name: "cut1image", widget: "image"}
      - {label: "Image 2", name: "cut2image", widget: "image"}
      - {label: "Image 3", name: "cut3image", widget: "image"}
      - {label: "Image 4", name: "cut4image", widget: "image"}
      - {label: "Image 5", name: "cut5image", widget: "image"}
      - {label: "Promotions (Orange Text)", name: "promos", widget: "string", required: false }
      - {label: "Info (Black Text)", name: "info", widget: "markdown", required: false}      
      - {label: "Important Info (Red Text)", name: "importantinfo", widget: "markdown", required: false}
      - {label: "More Info (Black Text)", name: "info2", widget: "markdown", required: false}  
      - {label: "Hours", name: "hours", widget: "markdown"}
      - {label: "Sylist 1 Image *Image must be square*", name: "stylist1image", widget: "image"}
      - {label: "Sylist 1 Name", name: "stylist1name", widget: "string"}
      - {label: "Sylist 1 Description", name: "stylist1description", widget: "markdown"}
      - {label: "Sylist 2 Image *Image must be square*", name: "stylist2image", widget: "image", required: false }
      - {label: "Sylist 2 Name", name: "stylist2name", widget: "string", required: false }
      - {label: "Sylist 2 Description", name: "stylist2description", widget: "markdown", required: false }
      - {label: "Sylist 3 Image *Image must be square*", name: "stylist3image", widget: "image", required: false }
      - {label: "Sylist 3 Name", name: "stylist3name", widget: "string", required: false }
      - {label: "Sylist 3 Description", name: "stylist3description", widget: "markdown", required: false }

  - name: "gallery"
    label: "Haircut Gallery"
    delete: false
    editor:
      preview: false
    folder: "gallerypage"
    sort: "title:asc"
    create: false
    slug: "{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "page2"}
      - {label: "Title", name: "title", widget: "string", tagname: "h1"}
      - {label: "Permalink", name: "permalink", widget: "hidden"}
      - {label: "Section", name: "section", widget: "hidden", default: "{{name}}"}      
      - {label: "Image 1", name: "gallery1image", widget: "image", required: false}
      - {label: "Image 2", name: "gallery2image", widget: "image", required: false}
      - {label: "Image 3", name: "gallery3image", widget: "image", required: false}
      - {label: "Image 4", name: "gallery4image", widget: "image", required: false}
      - {label: "Image 5", name: "gallery5image", widget: "image", required: false}
      - {label: "Image 6", name: "gallery6image", widget: "image", required: false}
      - {label: "Image 7", name: "gallery7image", widget: "image", required: false}
      - {label: "Image 8", name: "gallery8image", widget: "image", required: false}
      - {label: "Image 9", name: "gallery9image", widget: "image", required: false}
      - {label: "Image 10", name: "gallery10image", widget: "image", required: false}
      - {label: "Image 11", name: "gallery11image", widget: "image", required: false}
      - {label: "Image 12", name: "gallery12image", widget: "image", required: false}
      - {label: "Image 13", name: "gallery13image", widget: "image", required: false}
      - {label: "Image 14", name: "gallery14image", widget: "image", required: false}
      - {label: "Image 15", name: "gallery15image", widget: "image", required: false}
      - {label: "Image 16", name: "gallery16image", widget: "image", required: false}
      - {label: "Image 17", name: "gallery17image", widget: "image", required: false}
      - {label: "Image 18", name: "gallery18image", widget: "image", required: false}
      - {label: "Image 19", name: "gallery19image", widget: "image", required: false}
      - {label: "Image 20", name: "gallery20image", widget: "image", required: false}

